<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Pororoca.Desktop</AssemblyName>
    <OutputType>WinExe</OutputType>
    <EmitCompilerGeneratedFiles Condition="'$(Configuration)'=='Debug'">true</EmitCompilerGeneratedFiles>
    <!--
      line below will include INSTALLED_ON_WINDOWS preprocessor directive
      when "-p:PublishForInstallOnWindows" is specified in dotnet build, run or publish
    -->
    <DefineConstants Condition=" '$(PublishForInstallOnWindows)' == 'true' ">$(DefineConstants);INSTALLED_ON_WINDOWS</DefineConstants>
    <DefineConstants Condition=" '$(PublishForInstallOnDebian)' == 'true' ">$(DefineConstants);INSTALLED_ON_DEBIAN</DefineConstants>
    <DefineConstants Condition=" '$(UITestsEnabled)' == 'true' ">$(DefineConstants);UI_TESTS_ENABLED</DefineConstants>
    <EnableCompressionInSingleFile>True</EnableCompressionInSingleFile>
    <PublishReadyToRun>True</PublishReadyToRun>
    <!-- trimming properties begin -->
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>partial</TrimMode>
    <!-- below required for trimming on .NET 10 -->
    <Http3Support>true</Http3Support>
    <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
    <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
    <!-- disabling below because some Spanish-speaking countries use ',' decimal separator (Spain and most LATAM) and some use '.' (MX and Central America) -->
    <!--InvariantGlobalization>true</InvariantGlobalization-->
    <MetadataUpdaterSupport>false</MetadataUpdaterSupport>
    <EnableUnsafeUTF7Encoding>false</EnableUnsafeUTF7Encoding>
    <!-- trimming properties end -->
    <ApplicationIcon>Assets/pororoca_icon.ico</ApplicationIcon>
    <Version>3.9.1</Version>
    <FileVersion>$(Version)</FileVersion>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <Copyright>AlexandreHTRB</Copyright>
    <StartupObject>Pororoca.Desktop.Program</StartupObject>
    <!-- Licence also available at https://github.com/alexandrehtrb/Pororoca/LICENCE.md -->
  </PropertyGroup>
  <ItemGroup Condition="'$(PublishTrimmed)'=='true'">
    <TrimmableAssembly Include="Avalonia.Controls.ColorPicker" />
    <TrimmableAssembly Include="Avalonia.Themes.Simple" />
    <TrimmableAssembly Include="ColorTextBlock.Avalonia" />
    <TrimmableAssembly Include="Markdown.Avalonia.Tight" />
    <TrimmableAssembly Include="AlexandreHtrb.AvaloniaUITest" />
    <TrimmableAssembly Include="Pororoca.Domain" />
    <TrimmableAssembly Include="Pororoca.Domain.OpenAPI" />
    <TrimmableAssembly Include="Pororoca.Infrastructure" />
    <TrimmableAssembly Include="Microsoft.OpenApi" />
    <TrimmableAssembly Include="Microsoft.OpenApi.YamlReader" />
    <TrimmableAssembly Include="Xaml.Behaviors.Interactions.DragAndDrop.DataGrid"/>
    <TrimmableAssembly Include="Xaml.Behaviors.Interactions.DragAndDrop"/>
    <TrimmableAssembly Include="Xaml.Behaviors.Interactions.Draggable"/>
    <TrimmableAssembly Include="Xaml.Behaviors.Interactions.Custom"/>
    <TrimmableAssembly Include="Xaml.Behaviors.Avalonia"/>
    <TrimmableAssembly Include="Xaml.Behaviors.Interactivity"/>
    <TrimmableAssembly Include="Xaml.Behaviors.Interactions"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Pororoca.Domain\Pororoca.Domain.csproj" />
    <ProjectReference Include="..\Pororoca.Domain.OpenAPI\Pororoca.Domain.OpenAPI.csproj" />
    <ProjectReference Include="..\Pororoca.Infrastructure\Pororoca.Infrastructure.csproj" />
    <ProjectReference Include="..\Pororoca.Desktop.Localization.SourceGeneration\Pororoca.Desktop.Localization.SourceGeneration.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="./Localization/i18n_keys.json" />
    <AdditionalFiles Include="./Localization/en-gb.i18n_lang.json" />
    <AdditionalFiles Include="./Localization/de-de.i18n_lang.json" />
    <AdditionalFiles Include="./Localization/pt-br.i18n_lang.json" />
    <AdditionalFiles Include="./Localization/ru-ru.i18n_lang.json" />
    <AdditionalFiles Include="./Localization/it-it.i18n_lang.json" />
    <AdditionalFiles Include="./Localization/zh-cn.i18n_lang.json" />
    <AdditionalFiles Include="./Localization/es-mx.i18n_lang.json" />
    <AdditionalFiles Include="./Localization/pl-pl.i18n_lang.json" />
    <AdditionalFiles Include="./Localization/th-th.i18n_lang.json" />
  </ItemGroup>
  <!-- Removes UI tests code in release versions that are not flagged for UI tests -->
  <ItemGroup Condition="'$(Configuration)' == 'Release' And '$(UITestsEnabled)' != 'true'">
    <Compile Remove="UITesting\**" />
    <Content Include="UITesting\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="**\*.xaml.cs">
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
    <AvaloniaResource Include="**\*.xaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia"/>
    <PackageReference Include="Avalonia.Desktop"/>
    <PackageReference Include="Avalonia.ReactiveUI"/>
    <PackageReference Include="Avalonia.Themes.Fluent"/>
    <PackageReference Include="Avalonia.Controls.DataGrid"/>
    <PackageReference Include="Xaml.Behaviors.Interactions.DragAndDrop.DataGrid"/>
    <PackageReference Include="Xaml.Behaviors.Interactions.DragAndDrop"/>
    <PackageReference Include="Xaml.Behaviors.Interactions.Draggable"/>
    <PackageReference Include="Xaml.Behaviors.Interactions.Custom"/>
    <PackageReference Include="Xaml.Behaviors.Avalonia"/>
    <PackageReference Include="Xaml.Behaviors.Interactivity"/>
    <PackageReference Include="Xaml.Behaviors.Interactions"/>
    <PackageReference Include="AlexandreHtrb.AvaloniaUITest" Condition="'$(Configuration)'=='Debug' Or '$(UITestsEnabled)' == 'true'"/>
    <!--Condition below is needed to remove AvaloniaUI.DiagnosticsSupport package from build output in Release configuration.-->
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Condition="'$(Configuration)' == 'Debug'"/>
    <PackageReference Include="Avalonia.AvaloniaEdit"/>
    <PackageReference Include="AvaloniaEdit.TextMate"/>
    <PackageReference Include="TextMateSharp.Grammars"/>

    <PackageReference Include="ReactiveUI.Fody"/>
    <PackageReference Include="MessageBox.Avalonia"/>
  </ItemGroup>
</Project>
