<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Pororoca.Domain</RootNamespace>
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>False</IsAotCompatible>
    <!-- Licence also available at https://github.com/alexandrehtrb/Pororoca/LICENCE.md -->
  </PropertyGroup>

</Project>