<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Pororoca.Domain</RootNamespace>
    <IsTrimmable>True</IsTrimmable>
    <IsAotCompatible>True</IsAotCompatible>
    <!-- Licence also available at https://github.com/alexandrehtrb/Pororoca/LICENCE.md -->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pororoca.Domain\Pororoca.Domain.csproj"/>
    <PackageReference Include="Microsoft.OpenApi"/>
    <PackageReference Include="Microsoft.OpenApi.YamlReader"/>
  </ItemGroup>

</Project>
